[package]
name = "open-envault"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Local-first SOPS-compatible secrets for Git and Rust"
readme = "README.md"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
yaml_serde.workspace = true
sha2.workspace = true
aes-gcm.workspace = true
age.workspace = true
base64.workspace = true
hex.workspace = true
rand.workspace = true
zeroize.workspace = true
windows-sys.workspace = true

[dev-dependencies]
tempfile = "3"

[[bin]]
name = "oenv"
path = "src/main.rs"
